= WTFB
:experimental:

image:https://img.shields.io/badge/target-Blender_4.0-blue[Target: Blender 4.0]
image:https://img.shields.io/github/license/tjysunset/WTFB[]

Various personal tools for Blender.

http://github.com/tjysunset/WTFB/archive/main.zip[Download from the top-right green button].

== Save History

Automatically insert a dummy _Undo History_ entry whenever you save.
Useful for quickly reverting to your last save point.

Disabled by default; Enable in addon preferences.

== Operators

Find the operators with btn:[F3]. They are not added to any GUI menus.

=== Animation

Auto Group Channels:: Group ungrouped channels (generated by some addons) by bone name.
Clean Constant Channels:: Reduce near-constant channels to one keyframe, and optionally hide them.
[NOTE]
.What's the difference between `Clean Constant Channels` and Blender's built-in `Clean Channels`?
====
`Clean Channels` not only cleans the constant channels, but also forcibly simplifies all your other channels, while disrespecting cyclic F-Curves.
====
Find Forgotten F-Curves:: List channels that contain more than one keyframe, but all keyframes are set to constant or linear interpolation.
Normalize Quaternion Rotation:: Normalize quaternion rotations for selected bones in pose mode (doesn't affect animation keyframes).
Reset Bezier Handles:: For all selected channels, set all bezier keyframes to a horizontal 2-frame-wide "aligned" keyframe.
Select Left/Right Bezier Handles:: Select all left/right handles of visible bezier keyframes.

=== Misc

Toggle Viewport Focal Length:: Toggle active viewport focal length between 35mm and 50mm.
Toggle Viewport Shading:: Toggle active viewport shading between MatCap and flat + shadows + curvature.
