= WTFB
:experimental:

image:https://img.shields.io/badge/target-Blender_4.0-blue[Target: Blender 4.0]
image:https://img.shields.io/github/license/tjysunset/WTFB[]

Various personal tools for Blender.

http://github.com/tjysunset/WTFB/archive/main.zip[Download from the top-right green button].

== Save History

Automatically insert a dummy _Undo History_ entry whenever you save.
Useful for quickly reverting to your last save point.

Disabled by default; Enable in addon preferences.

== Operators

Find the operators with btn:[F3]. They are not added to any GUI menus.

=== Animation

Auto Group Channels:: Group ungrouped channels (generated by some addons) by bone name.
Clean Constant Channels:: Reduce near-constant channels to one keyframe, and optionally hide them.
[NOTE]
.What's the difference between `Clean Constant Channels` and Blender's built-in `Clean Channels`?
====
`Clean Channels` not only cleans the constant channels, but also forcibly simplifies all your other channels, while disrespecting cyclic F-Curves.
====
Find Forgotten F-Curves:: List channels that contain more than one keyframe, but all keyframes are set to constant or linear interpolation.
Normalize Quaternion Rotation:: Normalize quaternion rotations for selected bones in pose mode (doesn't affect animation keyframes).
Reset Bezier Handles:: For all selected channels, set all bezier keyframes to a horizontal 2-frame-wide "aligned" keyframe.
Select Left/Right Bezier Handles:: Select all left/right handles of visible bezier keyframes.

=== Mesh

Average Vertex Weights:: Average unlocked vertex weights for selected vertices in the active object. Useful for fixing automatic/transferred deformation weights on rigid parts. Supports LoopTools-style multi-edge-loop selection for gradient editing.
Move Vertex Weights:: Add one vertex group to another, and optionally clears the source group. Useful for cleaning normalized transferred weights.
[NOTE]
.Can't I just use the `Vertex Weight Mix` modifier for this purpose?
====
No, that crap ignores vertices not influenced by the target group.
====

=== Misc

Auto Pass Index:: Assign an unique pass index to every zero-indexed local material and object in file. Originally made for NPR, but practically useless since using this dysfunctional compositor for NPR is a joke.
Toggle Rest Position:: Toggle rest position for all armatures in scene. Note this action is not undoable outside of object mode, i.e. not undoable in its intended use case, but you could always toggle it again.
Toggle Viewport Focal Length:: Toggle active viewport focal length between 35mm and 50mm.
Toggle Viewport Shading:: Toggle active viewport shading between MatCap and flat + shadows + curvature.
